# Generated by Django 4.2.6 on 2024-05-26 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chat_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='response',
        ),
    ]
